"""initial_migration

Revision ID: 0056a08c18ab
Revises: 
Create Date: 2026-03-15 13:35:10.798573

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0056a08c18ab'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_products_category'), table_name='products')
    op.drop_index(op.f('idx_products_sku'), table_name='products')
    #op.drop_table('products')
    op.drop_index(op.f('idx_store_items_expiration'), table_name='store_items', postgresql_where='(expiration_date IS NOT NULL)')
    op.drop_index(op.f('idx_store_items_rfid'), table_name='store_items')
    op.drop_index(op.f('idx_store_items_status'), table_name='store_items')
    #op.drop_table('store_items')
    op.alter_column('catalog_products', 'unit',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'шт.'::character varying"))
    op.alter_column('catalog_products', 'min_threshold',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('10'))
    op.alter_column('catalog_products', 'critical_threshold',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('5'))
    op.alter_column('catalog_products', 'target_quantity',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('30'))
    op.drop_column('item_history', 'quantity_change')
    op.drop_column('item_history', 'notes')
    op.drop_constraint(op.f('tagged_items_product_id_fkey'), 'tagged_items', type_='foreignkey')
    op.create_foreign_key(None, 'tagged_items', 'catalog_products', ['product_id'], ['product_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tagged_items', type_='foreignkey')
    op.create_foreign_key(op.f('tagged_items_product_id_fkey'), 'tagged_items', 'catalog_products', ['product_id'], ['product_id'], ondelete='CASCADE')
    op.add_column('item_history', sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('item_history', sa.Column('quantity_change', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True))
    op.alter_column('catalog_products', 'target_quantity',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('30'))
    op.alter_column('catalog_products', 'critical_threshold',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('5'))
    op.alter_column('catalog_products', 'min_threshold',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('10'))
    op.alter_column('catalog_products', 'unit',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'шт.'::character varying"))
    op.create_table('store_items',
    sa.Column('item_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('item_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('rfid_uid', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'не_оплачен'::character varying"), autoincrement=False, nullable=False),
    sa.Column('manufactured_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('expiration_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('last_seen', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('current_quantity', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.CheckConstraint("status::text = ANY (ARRAY['не_оплачен'::character varying, 'оплачен'::character varying, 'просрочен'::character varying]::text[])", name=op.f('store_items_status_check')),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], name=op.f('store_items_product_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('item_id', name=op.f('store_items_pkey')),
    sa.UniqueConstraint('rfid_uid', name=op.f('store_items_rfid_uid_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('idx_store_items_status'), 'store_items', ['status'], unique=False)
    op.create_index(op.f('idx_store_items_rfid'), 'store_items', ['rfid_uid'], unique=False)
    op.create_index(op.f('idx_store_items_expiration'), 'store_items', ['expiration_date'], unique=False, postgresql_where='(expiration_date IS NOT NULL)')
    op.create_table('products',
    sa.Column('product_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('sku', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('unit', sa.VARCHAR(length=50), server_default=sa.text("'шт.'::character varying"), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('category', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('product_id', name=op.f('products_pkey')),
    sa.UniqueConstraint('sku', name=op.f('products_sku_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('idx_products_sku'), 'products', ['sku'], unique=False)
    op.create_index(op.f('idx_products_category'), 'products', ['category'], unique=False)
    # ### end Alembic commands ###
